function p = td_sharedcodeextras_pathdef
% TD_SHAREDCODEEXTRAS_PATHDEF - some paths you might want - Tom's shared code
%
% In your startup.m (or at the command line)
%
% cd C:\MATLAB\tjd-shared-code-extras\matlab % path to folder containing this file
% path(td_sharedcodeextras_pathdef,path);
%
% Tom Davidson (tjd@stanford.edu/tjd@alum.mit.edu) May 2010
 
path_to_repo = pwd; % since we cd'd here before running this

p = [...
    path_to_repo filesep pathsep ...
    path_to_repo filesep 'fkSegments' pathsep ...
    path_to_repo filesep 'spikeslpos_noexpt' pathsep ...
    path_to_repo filesep 'spikeslpos_multi' pathsep ...
    path_to_repo filesep 'util' pathsep ...
    path_to_repo filesep 'analysis' pathsep ...
    genpath([path_to_repo '/obj']), ... % get subfolders too
    genpath([path_to_repo '/spikeslpos']), ... % get subfolders too...
];

% pretty it up, Matlab actually will accept either slash
p = strrep(p, '/', filesep);